export const SET_USER_NAME="SET_USER_NAME"
export const SET_STAGE="SET_STAGE"
export const SET_STATE="SET_STATE"
export const SET_UNDO_CORRECT_WORDS="SET_UNDO_CORRECT_WORDS"
export const SET_CORRECT_WORDS="SET_UNDO_CORRECT_WORDS"
export const SET_CORRECT_ANSWERS="SET_CORRECT_ANSWERS"





